### ISSUE TITLE
Randomly deleted ~/.multigit files

### ISSUE THREAD

**Issue by scizzorz** [scizzorz/multigit#2]
Sometimes when calling `mg rm ...` my entire `~/.multigit` file is removed. I'm not entirely sure what causes it yet, so I can't reproduce it, but I suspect it has something to do with `uniq(1)`.

**Comment by philipdexter** [comment]
```
$ ./multigit.sh addr ~/projects
adding /home/philip/projects/stuff
adding /home/philip/projects/stuff2
.....
adding /home/philip/projects/stuffn

$ ./multigit.sh rm ~/projects
removing /home/philip/projects

$ ./multigit.sh list
[empty]
```

This has to do with the use of grep. Can fix it with adding a `\$` at the end of the expression. Pull request on its way.

**Comment by scizzorz** [comment]
Found the bug: trying to remove a path that doesn't exist makes `realpath` print an empty string, which makes `grep -v` filter everything out of the file.

**Comment by philipdexter** [comment]
Nice find. Also something worth noting: `uniq` will only filter matching lines that are right next to each other. Could either sort the file first (which might be a downside if the user wanted a specific ordering to his git commands) or run: `awk '!x[$0]++' ~/.multigit` which preserves order.

**Comment by scizzorz** [comment]
Noted and fixed.
