### ISSUE TITLE
Support remote repositories

### ISSUE THREAD

**Issue by scizzorz** [scizzorz/multigit#6]
It might be nice to track remote repositories as well, eg being able to automatically pull new changes on a dozen different machines. In the `~/.multigit` file it could just use `ssh` syntax, eg `host:path`. If `multigit` encounters a colon in a path, it splits it and runs something like `ssh $host; cd $path; git $@; echo` instead of `pushd $path; git $@; popd; echo`

**Comment by philipdexter** [comment]
I thought of this myself once. Are you working on it now?

**Comment by scizzorz** [comment]
Not at the moment. Just recording it for the future, although you can feel free to start it.
