### ISSUE TITLE
[on turbo] A mechanism to namespace the entire codebase

### ISSUE THREAD

**Issue by scizzorz** [scizzorz/multigit#7]
_(this is only applicable to the `turbo` branch)_

Hopefully it will prevent name collisions with some editors (*cough* @philipdexter *cough*).

I think it would be ideal to have some sort of `mg_namespace` environment variable, and then have all of the `mg` functions named after that:

``` bash
mg_namespace="mg"
...
function ${mg_namespace} {
    ...main mg function...
}
...
function ${mg_namespace}-add {
    ...mg add function...
}
```

If we just source a file like `~/.multigitrc` in the new `multigit.sh`, that should namespace the rest of it accordingly. Consequently, users with existing `mg` commands / methods would only need to make a `~/.multigitrc` and would never have to modify the source to use it. Unfortunately, my initial searches didn't pop up with anything useful and function identifiers seems to be the only place bash _won't_ let you expand variables...

**Comment by scizzorz** [comment]
Or perhaps everything should just be namespaced as `multigit` and then let the user alias it to whatever they want... I doubt `multigit` will have any naming conflicts. Ever.

**Comment by philipdexter** [comment]
If you prefer `mg', then we should keep it at that. I'll think of something in the meantime. Very few people use mg as far as I know.

**Comment by scizzorz** [comment]
Nah, I totally over-thought this when I opened the issue. Aliasing is perfectly acceptable.
