### ISSUE TITLE
Git submodules should be included when recursively searching

### ISSUE THREAD

**Issue by scizzorz** [scizzorz/multigit#9]
I patched a tiny bug just now, but submodules should be indexed as well instead of just ignored. The problem is that in a submodule, `.git` is a file and not a directory, so `realpath` complains about not being able to access `blah/blah/.git/..`. I imagine there must be some way to `realpath` the path with `.git` stripped from the end, but I'm busy with something else at the moment.

**Comment by philipdexter** [comment]
I've never worked with submodules before in-depth. It's actually just a file? Interestingggg

**Comment by philipdexter** [comment]
I took a shot at it

**Comment by scizzorz** [comment]
Your code reminded me that `dirname` exists, which works on directories too. I tried just piping it into the `xargs` thing and eventually figured out that `find` can essentially `dirname` all of its output anyway. Problem solved!

**Comment by philipdexter** [comment]
Great! The simpler the better. I'll get another commit in someday!
